# Generated by Django 6.0.3 on 2026-05-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0002_edital_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
    ]
