# Generated by Django 6.0.3 on 2026-05-30 09:37

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0003_alter_edital_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edital',
            options={'verbose_name': 'Edital', 'verbose_name_plural': 'Editais'},
        ),
        migrations.RemoveField(
            model_name='edital',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='edital',
            name='campus',
            field=models.CharField(choices=[('GERAL', 'Geral / Todos os Campi'), ('DIAMANTINA', 'Diamantina'), ('UNAI', 'Unaí'), ('MUCURI', 'Mucuri (Teófilo Otoni)'), ('JANAUBA', 'Janaúba')], default='GERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='edital',
            name='descricao',
            field=ckeditor.fields.RichTextField(default=1, help_text='Descrição detalhada sobre o edital.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edital',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.CreateModel(
            name='DocumentoEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Edital de Abertura, Resultado Preliminar, etc.', max_length=500)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='editais/documentos/')),
                ('link', models.URLField(blank=True, help_text='Link externo opcional (ex: Google Drive, site da UFVJM).', null=True)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='editais.edital')),
            ],
            options={
                'verbose_name': 'Documento do Edital',
                'verbose_name_plural': 'Documentos dos Editais',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
