# Generated by Django 6.0.3 on 2026-05-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('banner', models.ImageField(upload_to='eventos/')),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField()),
                ('link_ingresso', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
