# Generated by Django 6.0.3 on 2026-05-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se desmarcado, o evento será movido para a seção de encerrados.'),
        ),
    ]
