# Generated by Django 6.0.3 on 2026-03-30 19:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dce_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercicioFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(default=2026, unique=True, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)])),
                ('aberto', models.BooleanField(default=True, help_text='Se desmarcado, o ano está selado e não aceita novas modificações.')),
                ('relatorio_pdf', models.FileField(blank=True, help_text='Upload do relatório final de prestação de contas assinado.', null=True, upload_to='financeiro/relatorios/')),
            ],
            options={
                'verbose_name': 'Exercício Financeiro',
                'verbose_name_plural': 'Exercícios Financeiros',
                'ordering': ['-ano'],
            },
        ),
        migrations.AlterModelOptions(
            name='financeiro',
            options={'ordering': ['-data'], 'verbose_name': 'Movimentação Financeira', 'verbose_name_plural': 'Financeiro'},
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='exercicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='dce_portal.exerciciofinanceiro'),
        ),
    ]
