# Generated by Django 6.0.3 on 2026-05-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='campus',
            field=models.CharField(choices=[('GERAL', 'Geral / Todos os Campi'), ('DIAMANTINA', 'Diamantina'), ('UNAI', 'Unaí'), ('MUCURI', 'Mucuri (Teófilo Otoni)'), ('JANAUBA', 'Janaúba')], default='GERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='noticia',
            name='tags',
            field=models.CharField(blank=True, help_text='Insira os assuntos separados por vírgula. Ex: Assuntos Estudantis, Bolsas, Eventos', max_length=255),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
