# Generated by Django 6.0.3 on 2026-05-25 16:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExercicioFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(default=2026, unique=True, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)])),
                ('aberto', models.BooleanField(default=True, help_text='Se desmarcado, o ano está selado e não aceita novas modificações.')),
                ('relatorio_pdf', models.FileField(blank=True, help_text='Upload do relatório final de prestação de contas assinado.', null=True, upload_to='financeiro/relatorios/')),
            ],
            options={
                'verbose_name': 'Exercício Financeiro',
                'verbose_name_plural': 'Exercícios Financeiros',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=7)),
                ('data', models.DateField()),
                ('exercicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='financeiro.exerciciofinanceiro')),
            ],
            options={
                'verbose_name': 'Movimentação Financeira',
                'verbose_name_plural': 'Financeiro',
                'ordering': ['-data'],
            },
        ),
    ]
