# Generated by Django 6.0.3 on 2026-05-27 10:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeiro',
            options={'ordering': ['-data', '-id'], 'verbose_name': 'Movimentação Financeira', 'verbose_name_plural': 'Fluxo de Caixa (Lançamentos)'},
        ),
        migrations.AddField(
            model_name='exerciciofinanceiro',
            name='saldo_inicial_transportado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor automatizado pelo sistema com base no fechamento do ano anterior.', max_digits=12, verbose_name='Saldo Inicial (Vindo do Ano Anterior)'),
        ),
        migrations.AlterField(
            model_name='exerciciofinanceiro',
            name='aberto',
            field=models.BooleanField(default=True, help_text='Se desmarcado, o ano financeiro é selado, gerando o travamento dos lançamentos.', verbose_name='Status Aberto'),
        ),
        migrations.AlterField(
            model_name='exerciciofinanceiro',
            name='ano',
            field=models.PositiveIntegerField(default=2026, unique=True, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano de Exercício'),
        ),
        migrations.AlterField(
            model_name='exerciciofinanceiro',
            name='relatorio_pdf',
            field=models.FileField(blank=True, help_text='Upload do demonstrativo contábil assinado obrigatório para encerrar o ano.', null=True, upload_to='financeiro/relatorios/', verbose_name='Relatório de Prestação de Contas (PDF)'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='data',
            field=models.DateField(verbose_name='Data da Movimentação'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição do Lançamento'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='exercicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='financeiro.exerciciofinanceiro', verbose_name='Ano do Exercício'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Receita (Entrada)'), ('SAIDA', 'Despesa (Saída)')], max_length=7, verbose_name='Natureza do Fluxo'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor (R$)'),
        ),
    ]
