# Generated by Django 6.0.3 on 2026-05-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_financeiro_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciciofinanceiro',
            name='aberto',
            field=models.BooleanField(default=True, help_text='Se desmarcado, o ano financeiro é selado, travando novos lançamentos.', verbose_name='Status Aberto'),
        ),
        migrations.AlterField(
            model_name='exerciciofinanceiro',
            name='saldo_inicial_transportado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor calculado automaticamente com base no encerramento do exercício anterior. Bloqueado para edição manual.', max_digits=12, verbose_name='Saldo Inicial (Transportado Automaticamente)'),
        ),
    ]
