# Generated by Django 6.0.3 on 2026-05-27 10:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_exerciciofinanceiro_aberto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeiro',
            options={'ordering': ['-data', '-id'], 'verbose_name': 'Movimentação Financeira', 'verbose_name_plural': 'Livro Caixa (Lançamentos)'},
        ),
        migrations.RemoveField(
            model_name='exerciciofinanceiro',
            name='relatorio_pdf',
        ),
        migrations.AddField(
            model_name='exerciciofinanceiro',
            name='saldo_final_fechamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Final Consolidado no Fechamento'),
        ),
        migrations.AddField(
            model_name='exerciciofinanceiro',
            name='total_entrada_fechamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total de Entradas no Fechamento'),
        ),
        migrations.AddField(
            model_name='exerciciofinanceiro',
            name='total_saida_fechamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total de Saídas no Fechamento'),
        ),
        migrations.AlterField(
            model_name='exerciciofinanceiro',
            name='aberto',
            field=models.BooleanField(default=True, help_text='Se desmarcado, o ano contábil é selado e o balanço é congelado em definitivo pelo sistema.', verbose_name='Status de Movimentação'),
        ),
        migrations.AlterField(
            model_name='exerciciofinanceiro',
            name='saldo_inicial_transportado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor automatizado pelo sistema. Lucro ou Dívida herdada do exercício passado.', max_digits=12, verbose_name='Saldo Inicial (Vindo do Ano Anterior)'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='data',
            field=models.DateField(verbose_name='Data do Lançamento'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição Clara do Lançamento'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='financeiro.exerciciofinanceiro', verbose_name='Exercício Fiscal'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Receita (Entrada em Caixa)'), ('SAIDA', 'Despesa (Saída de Caixa)')], max_length=7, verbose_name='Natureza do Fluxo'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Valor Operado (R$)'),
        ),
    ]
