# Generated by Django 6.0.3 on 2026-05-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('tipo', models.CharField(choices=[('EDITAL', 'Edital'), ('TRANSPARENCIA', 'Transparência'), ('INSTITUCIONAL', 'Institucional')], max_length=20)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
