# Generated by Django 6.0.3 on 2026-05-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('TRANSPARENCIA', 'Transparência'), ('INSTITUCIONAL', 'Institucional')], max_length=20),
        ),
    ]
